import os
import subprocess,re
os.system("mode con:cols=50 lines=100")

def exit():
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 01>null")
	os.system("echo T h a n k s     F o r    U s i n g    T h i s    S o f t w a r e ")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo      c o d e    b y    s a c h e e r a    m a d u s h a n")
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("color 03")
	os.system("timeout 01>null")
	os.system("color 04")
	os.system("timeout 01>null")
	os.system("color 05")
	os.system("timeout 01>null")
	os.system("color 06")
	os.system("timeout 01>null")
	os.system("color 07")
	os.system("timeout 01>null")
	os.system("color 02")
	os.system("timeout 01>null")
	os.system("exit")


def startlogo():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo.")
	os.system("echo                      wifi password viewer                       ")
	os.system("echo.")
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("echo      c o d e    b y    s a c h i r a    m a d h u s h a n")
	os.system("timeout 01>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 01>null")
	os.system("color 03")
	os.system("timeout 01>null")
	os.system("color 04")
	os.system("timeout 01>null")
	os.system("color 05")
	os.system("timeout 01>null")
	os.system("color 06")
	os.system("timeout 01>null")
	os.system("color 07")
	os.system("timeout 01>null")
	os.system("color 02")
	os.system("timeout 01>null")


def niklogo():
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo                          wifi password viewer                       ")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo              c o d e    b y    s a c h i r a    m a d h u s h a n")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 01>null")

def profiles():
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////            PROFILES  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("netsh wlan show profiles")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo [1]-View Password")
	os.system("echo [2]-Exit")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 02>null")
	y=input("[+]-Choose Option :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	if y=="1":
		global x
		x=input("[+]-Enter Profile Name :")

		os.system("echo.")
		os.system("echo.")
		os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
		os.system("timeout 02>null")
		os.system("cls")
		niklogo()
		password()


	else:

		os.system("cls")
		exit()


def password():
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("echo --------------------------------------------------------------------------------")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo //////////////////////            PASSWORDS  	    	/////////////////////// ")
	os.system("echo /                                                                              /")
	os.system("echo /                                                                              /")
	os.system("echo --------------------------------------------------------------------------------")	
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo.")
	os.system("echo.")
	try:
		c=subprocess.check_output("netsh wlan show profiles name="+x+" key=clear",shell=True)
	except:
		print("[?]error:-Wrong Profile Name....please Try Again...")
		os.system("timeout 02>null")
		profiles()

	out=re.search(r"(?:Key Content\s*:\s)(.*)()",str(c))
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("echo --------------------- Password Is:"+out.group(1)+" -------------------" )
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	os.system("timeout 02>null")
	os.system("echo.")
	os.system("echo.")
	os.system("echo [1]-Go Back")
	os.system("echo [2]-Exit")
	os.system("echo.")
	os.system("echo.")
	os.system("echo.")
	os.system("timeout 02>null")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

	os.system("echo.")
	os.system("echo.")
	d=input("[+]-Choose Option :")
	os.system("echo.")
	os.system("echo.")
	os.system("echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
	if d=="1":
		os.system("timeout 02>null")
		os.system("cls")
		niklogo()
		profiles()
	else:
		os.system("cls")
		exit()

def program():
	startlogo()
	profiles()

program()